# Generated by Django 5.2.1 on 2025-06-02 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='cart_items', to='accounts.cart'),
            preserve_default=False,
        ),
    ]
