# Generated by Django 5.2.1 on 2025-06-18 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_is_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_confirmed',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cart_items', to='accounts.cart'),
        ),
    ]
